import os

CONFIG_DIRECTORY = os.path.dirname(__file__)

PYLINT_CONFIG_NAME = '.pylintrc'
FLAKE8_CONFIG_NAME = '.flake8'

DEFAULT_PYLINT_CONFIG_PATH = os.path.join(CONFIG_DIRECTORY, PYLINT_CONFIG_NAME)
DEFAULT_FLAKE8_CONFIG_PATH = os.path.join(CONFIG_DIRECTORY, FLAKE8_CONFIG_NAME)
